language: python
python:
  - "3.6"

services:
  - docker

script:
  - docker-compose up -d
  - scripts/wait-for-it.sh airflow:8080 --timeout=300 --strict -- echo "airflow is up"
  - docker exec -ti airflow sh -c "python dags/reviews_dag.py" 
