version: '3.7'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - POSTGRES_HOST_AUTH_METHOD=trust
        ports:
            - 5432:5432            
        volumes:
            - ./initialize/database_user.sql:/docker-entrypoint-initdb.d/database_user.sql
            - ./initialize/dwh_tables.sql:/docker-entrypoint-initdb.d/dwh_tables.sql
            - D:/dataset/converted/metadata.json:/metadata.json
        logging:
           options:
               max-size: 10m
               max-file: "3"